In [1]:
import boto3
import pandas as pd

In [2]:
s3 = boto3.client("s3")
print ("s3 connect successfully")

s3 connect successfully

In [3]:
bucket = "blinkit-sales-performance"
file_key = "raw/blinkit_delivery_performance.csv"
print ("connected successfully")

connected successfully

In [44]:
obj = s3.get_object (Bucket=bucket, Key=file_key)
raw_data = pd.read_csv (obj['Body'])

In [45]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic
...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,NaN
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,NaN
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic

In [46]:
print(raw_data.columns.tolist())

['order_id', 'delivery_partner_id', 'promised_time', 'actual_time', 'delivery_time_minutes', 'distance_km', 'delivery_status', 'reasons_if_delayed']

In [47]:
raw_data.info

<bound method DataFrame.info of         order_id  delivery_partner_id        promised_time  \
0     1961864118                63230  2024-07-17 08:52:01
1     1549769649                14983  2024-05-28 13:25:29
2     9185164487                39859  2024-09-23 13:25:12
3     9644738826                61497  2023-11-24 16:34:56
4     5427684290                84315  2023-11-20 05:17:39
...          ...                  ...                  ...
4995  1669690997                90914  2023-12-25 16:05:20
4996  8340761903                27952  2023-11-27 09:38:43
4997  5936301790                 9590  2024-06-21 19:23:09
4998  5710579377                29940  2024-06-06 15:12:13
4999  2494813730                32851  2023-08-23 12:20:18

              actual_time  delivery_time_minutes  distance_km delivery_status  \
0     2024-07-17 08:47:01                   -5.0         0.96         On Time
1     2024-05-28 13:27:29                    2.0         0.98         On Time
2     2024-09-23 13:29:12                    4.0         3.83         On Time
3     2023-11-24 16:33:56                   -1.0         2.76         On Time
4     2023-11-20 05:18:39                    1.0         2.63         On Time
...                   ...                    ...          ...             ...
4995  2023-12-25 16:10:20                    5.0         1.86         On Time
4996  2023-11-27 09:36:43                   -2.0         3.31         On Time
4997  2024-06-21 19:26:09                    3.0         2.44         On Time
4998  2024-06-06 15:10:13                   -2.0         1.76         On Time
4999  2023-08-23 12:21:18                    1.0         2.70         On Time

     reasons_if_delayed
0                   NaN
1               Traffic
2               Traffic
3                   NaN
4               Traffic
...                 ...
4995            Traffic
4996                NaN
4997            Traffic
4998                NaN
4999            Traffic

[5000 rows x 8 columns]>

In [48]:
raw_data["reasons_if_delayed"] = raw_data["reasons_if_delayed"].fillna('Unknown')

In [49]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,Unknown
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,Unknown
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic
...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic

In [50]:
raw_data.drop_duplicates()
raw_data.isnull()

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False

In [51]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,Unknown
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,Unknown
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic
...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic

In [52]:
type ("actual_time")

str

In [53]:
raw_data["promised_time"] = pd.to_datetime(raw_data["promised_time"], errors="coerce")
raw_data["actual_time"] = pd.to_datetime(raw_data["actual_time"], errors="coerce")

In [54]:
type ("actual_time")

str

In [55]:
print (raw_data.dtypes)

order_id                          int64
delivery_partner_id               int64
promised_time            datetime64[us]
actual_time              datetime64[us]
delivery_time_minutes           float64
distance_km                     float64
delivery_status                     str
reasons_if_delayed                  str
dtype: object

In [70]:
raw_data["delayed_times"] = raw_data["actual_time"]-raw_data["promised_time"]

In [71]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed,delayed_times
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,Unknown,-1 days +23:55:00
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic,0 days 00:02:00
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic,0 days 00:04:00
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,Unknown,-1 days +23:59:00
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic,0 days 00:01:00
...,...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic,0 days 00:05:00
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown,-1 days +23:58:00
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic,0 days 00:03:00
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown,-1 days +23:58:00
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic,0 days 00:01:00

In [72]:
raw_data["delayed_times"].min()

Timedelta('-1 days +23:55:00')

In [73]:
raw_data["delayed_times"] = raw_data["delayed_times"].replace(to_replace=-1,value=1)

In [74]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed,delayed_times
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,Unknown,-1 days +23:55:00
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic,0 days 00:02:00
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic,0 days 00:04:00
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,Unknown,-1 days +23:59:00
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic,0 days 00:01:00
...,...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic,0 days 00:05:00
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown,-1 days +23:58:00
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic,0 days 00:03:00
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown,-1 days +23:58:00
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic,0 days 00:01:00

In [75]:
raw_data["delayed_times"].unique()

<TimedeltaArray>
['-1 days +23:55:00',   '0 days 00:02:00',   '0 days 00:04:00',
 '-1 days +23:59:00',   '0 days 00:01:00',   '0 days 00:03:00',
   '0 days 00:07:00', '-1 days +23:58:00',   '0 days 00:12:00',
   '0 days 00:11:00', '-1 days +23:57:00',   '0 days 00:08:00',
   '0 days 00:13:00',   '0 days 00:26:00',   '0 days 00:22:00',
 '-1 days +23:56:00',   '0 days 00:00:00',   '0 days 00:15:00',
   '0 days 00:09:00',   '0 days 00:19:00',   '0 days 00:14:00',
   '0 days 00:20:00',   '0 days 00:05:00',   '0 days 00:06:00',
   '0 days 00:16:00',   '0 days 00:27:00',   '0 days 00:21:00',
   '0 days 00:24:00',   '0 days 00:25:00',   '0 days 00:18:00',
   '0 days 00:10:00',   '0 days 00:29:00',   '0 days 00:17:00',
   '0 days 00:23:00',   '0 days 00:28:00',   '0 days 00:30:00']
Length: 36, dtype: timedelta64[us]

In [76]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed,delayed_times
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,Unknown,-1 days +23:55:00
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic,0 days 00:02:00
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic,0 days 00:04:00
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,Unknown,-1 days +23:59:00
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic,0 days 00:01:00
...,...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic,0 days 00:05:00
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown,-1 days +23:58:00
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic,0 days 00:03:00
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown,-1 days +23:58:00
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic,0 days 00:01:00

In [77]:
raw_data[raw_data["delayed_times"]==1]

Empty DataFrame
Columns: [order_id, delivery_partner_id, promised_time, actual_time, delivery_time_minutes, distance_km, delivery_status, reasons_if_delayed, delayed_times]
Index: []

In [78]:
raw_data["delayed_times"].unique()

<TimedeltaArray>
['-1 days +23:55:00',   '0 days 00:02:00',   '0 days 00:04:00',
 '-1 days +23:59:00',   '0 days 00:01:00',   '0 days 00:03:00',
   '0 days 00:07:00', '-1 days +23:58:00',   '0 days 00:12:00',
   '0 days 00:11:00', '-1 days +23:57:00',   '0 days 00:08:00',
   '0 days 00:13:00',   '0 days 00:26:00',   '0 days 00:22:00',
 '-1 days +23:56:00',   '0 days 00:00:00',   '0 days 00:15:00',
   '0 days 00:09:00',   '0 days 00:19:00',   '0 days 00:14:00',
   '0 days 00:20:00',   '0 days 00:05:00',   '0 days 00:06:00',
   '0 days 00:16:00',   '0 days 00:27:00',   '0 days 00:21:00',
   '0 days 00:24:00',   '0 days 00:25:00',   '0 days 00:18:00',
   '0 days 00:10:00',   '0 days 00:29:00',   '0 days 00:17:00',
   '0 days 00:23:00',   '0 days 00:28:00',   '0 days 00:30:00']
Length: 36, dtype: timedelta64[us]

In [79]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed,delayed_times
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,Unknown,-1 days +23:55:00
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic,0 days 00:02:00
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic,0 days 00:04:00
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,Unknown,-1 days +23:59:00
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic,0 days 00:01:00
...,...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic,0 days 00:05:00
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown,-1 days +23:58:00
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic,0 days 00:03:00
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown,-1 days +23:58:00
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic,0 days 00:01:00

In [80]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed,delayed_times
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,Unknown,-1 days +23:55:00
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic,0 days 00:02:00
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic,0 days 00:04:00
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,Unknown,-1 days +23:59:00
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic,0 days 00:01:00
...,...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic,0 days 00:05:00
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown,-1 days +23:58:00
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic,0 days 00:03:00
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown,-1 days +23:58:00
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic,0 days 00:01:00

In [81]:
raw_data.duplicated().sum()

np.int64(0)

In [82]:
print(raw_data.columns.tolist())

['order_id', 'delivery_partner_id', 'promised_time', 'actual_time', 'delivery_time_minutes', 'distance_km', 'delivery_status', 'reasons_if_delayed', 'delayed_times']

In [89]:
raw_data["on_time_rate"] = (
    raw_data[raw_data["delivery_status"] == "On Time"]
    .groupby("delivery_partner_id")
    .size()
    /
    raw_data.groupby("delivery_partner_id").size()
) * 100

on_time_rate.sort_values()

delivery_partner_id
43       100.0
66093    100.0
66096    100.0
66143    100.0
66152    100.0
         ...
99752      NaN
99820      NaN
99889      NaN
99898      NaN
99968      NaN
Length: 5000, dtype: float64

In [91]:
 raw_data["on_time_rate"] =  raw_data["on_time_rate"].fillna("Not Bad")

In [92]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed,delayed_times,on_time_rate
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,Unknown,-1 days +23:55:00,Not Bad
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic,0 days 00:02:00,Not Bad
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic,0 days 00:04:00,Not Bad
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,Unknown,-1 days +23:59:00,Not Bad
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic,0 days 00:01:00,Not Bad
...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic,0 days 00:05:00,Not Bad
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown,-1 days +23:58:00,Not Bad
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic,0 days 00:03:00,Not Bad
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown,-1 days +23:58:00,Not Bad
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic,0 days 00:01:00,Not Bad

In [99]:
raw_data["on_time_rate"].dtype

dtype('O')

In [100]:
raw_data["on_time_rate"] = pd.to_numeric(
    raw_data["on_time_rate"],
    errors="coerce"
)

In [103]:
raw_data=raw_data.sort_values(by="on_time_rate",ascending = True)

In [105]:
raw_data ["on_time_rate"] = raw_data["on_time_rate"].fillna(0)

In [110]:
raw_data

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed,delayed_times,on_time_rate
43,5630957897,14408,2024-06-18 07:32:42,2024-06-18 07:36:42,4.0,3.92,On Time,Traffic,0 days 00:04:00,100.0
3274,1441735184,50605,2024-10-31 15:20:54,2024-10-31 15:25:54,5.0,2.86,On Time,Traffic,0 days 00:05:00,100.0
3302,2254923956,71496,2024-08-19 19:12:40,2024-08-19 19:35:40,23.0,0.52,Significantly Delayed,Traffic,0 days 00:23:00,100.0
3304,9467422683,23501,2023-09-21 00:11:07,2023-09-21 00:10:07,-1.0,2.96,On Time,Unknown,-1 days +23:59:00,100.0
3350,8589621333,21113,2023-10-01 14:00:52,2023-10-01 13:57:52,-3.0,0.97,On Time,Unknown,-1 days +23:57:00,100.0
...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic,0 days 00:05:00,0.0
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,Unknown,-1 days +23:58:00,0.0
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic,0 days 00:03:00,0.0
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,Unknown,-1 days +23:58:00,0.0
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic,0 days 00:01:00,0.0

In [114]:
raw_data.to_csv("Cleaned_sales_perfomance.csv")

In [115]:
s3.upload_file("Cleaned_sales_perfomance.csv",bucket,"processed/Cleaned_sales_perfomance.csv")
print ("upload successfully")

upload successfully